version: 2.1
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/node:10-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Docker Build
          command: |
            docker build --tag goapp .
      - run:
          name: Docker Run
          command: |
            docker run goapp
            
      - run:
          name: Docker Push
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
            echo $DOCKERHUB_USERNAME
