version: 2.1
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/node:10-browsers
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Build
          command: |
            docker build --tag goapp .
      - run:
          name: Docker Run
          command: |
            docker run goapp
            
      - run:
          name: Docker Push
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
            docker tag goapp $DOCKERHUB_USER/circleci-build:$TAG
            docker push $DOCKERHUB_USER/circleci-build
  