version: 2.1
workflows:
  build:
    jobs:
      - build:
          context:
            - DOCKERHUB_USERNAME

jobs:
  build:
    environment:
      IMAGE_NAME: jimareed/circleci-build
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Docker Build
          command: |
            docker build --tag goapp .
      - run:
          name: Docker Run
          command: |
            docker run goapp
            
      - run:
          name: Docker Push
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker tag goapp $DOCKERHUB_USERNAME/circleci-build:$TAG
            docker tag goapp $DOCKERHUB_USERNAME/circleci-build:latest
            docker push $DOCKERHUB_USERNAME/circleci-build:$TAG
            docker push $DOCKERHUB_USERNAME/circleci-build:latest
